"""
Word pair bank for the Undercover game.
Each entry is (civilian_word, undercover_word) - close enough that the
undercover player can bluff, different enough that sharp descriptions
expose them. 80 pairs per category, shuffled fresh every round.
"""
import random

WORD_BANK = {
    "movies": [
        ("Harry Potter", "Narnia"),
        ("The Conjuring", "Sinister"),
        ("Up", "Inside Out"),
        ("Chappie", "I Robot"),
        ("John Wick", "Nobody"),
        ("Fantastic Beasts", "Narnia"),
        ("The Lion King", "Jungle Book"),
        ("Spider-Man", "Superman"),
        ("Fast & Furious", "Baby Driver"),
        ("Sultan", "Chak De India"),
        ("The Vampire Diaries", "Underworld"),
        ("Kuch Kuch Hota Hai", "Mohabbatein"),
        ("Zindagi Na Milegi Dobara", "Rock On"),
        ("The Vampire Diaries", "Van Helsing"),
        ("Grease", "Pitch Perfect"),
        ("Encanto", "Tangled"),
        ("Dilwale Dulhania Le Jayenge", "Kabhi Khushi Kabhie Gham"),
        ("Dilwale Dulhania Le Jayenge", "Kuch Kuch Hota Hai"),
        ("Alien", "Predator"),
        ("Kuch Kuch Hota Hai", "Kabhi Khushi Kabhie Gham"),
        ("Toy Story", "Monsters Inc"),
        ("Rockstar", "Wake Up Sid"),
        ("Dilwale Dulhania Le Jayenge", "Mohabbatein"),
        ("Kung Fu Panda", "Madagascar"),
        ("Avengers", "Justice League"),
        ("Interstellar", "The Prestige"),
        ("Star Wars", "Dune"),
        ("Swades", "Chak De India"),
        ("3 Idiots", "Munna Bhai MBBS"),
        ("Avatar", "Justice League"),
        ("Dangal", "Bhaag Milkha Bhaag"),
        ("Zindagi Na Milegi Dobara", "Yeh Jawaani Hai Deewani"),
        ("John Wick", "The Equalizer"),
        ("Rocky", "Million Dollar Baby"),
        ("Need for Speed", "Gone in 60 Seconds"),
        ("Final Destination", "The Ring"),
        ("Baahubali", "RRR"),
        ("The Lion King", "Tarzan"),
        ("Fast & Furious", "Need for Speed"),
        ("Titanic", "The Notebook"),
        ("Avatar", "Avengers"),
        ("Madagascar", "Ice Age"),
        ("The Hobbit", "Eragon"),
        ("Soul", "Inside Out"),
        ("Annabelle", "Sinister"),
        ("Tenet", "The Prestige"),
        ("King Kong", "Rampage"),
        ("Eragon", "Willow"),
        ("Batman", "Iron Man"),
        ("Zindagi Na Milegi Dobara", "Dil Chahta Hai"),
        ("Cinderella", "Snow White"),
        ("Moana", "Tangled"),
        ("Dil Chahta Hai", "Yeh Jawaani Hai Deewani"),
        ("Titanic", "A Star Is Born"),
        ("Captain Marvel", "Shazam"),
        ("RoboCop", "I Robot"),
        ("Pirates of the Caribbean", "Indiana Jones"),
        ("Mission Impossible", "Kingsman"),
        ("La La Land", "A Star Is Born"),
        ("National Treasure", "The Mummy"),
        ("Coco", "Soul"),
        ("Rockstar", "Tamasha"),
        ("Finding Nemo", "Monsters Inc"),
        ("Joker", "The Batman"),
        ("Get Out", "A Quiet Place"),
        ("Lord of the Rings", "Willow"),
        ("Doctor Strange", "Ant-Man"),
        ("Us", "Hereditary"),
        ("Chhichhore", "Munna Bhai MBBS"),
        ("Rocky", "Southpaw"),
        ("Percy Jackson", "Fantastic Beasts"),
        ("The Batman", "V for Vendetta"),
        ("Lagaan", "Swades"),
        ("Baahubali", "Pushpa"),
        ("Star Wars", "Guardians of the Galaxy"),
        ("Insidious", "Annabelle"),
        ("Lord of the Rings", "Eragon"),
        ("Alien", "The Thing"),
        ("Us", "A Quiet Place"),
        ("The Matrix", "Ready Player One"),
    ],
    "actors": [
        ("Hrithik Roshan", "Tiger Shroff"),
        ("Kristen Stewart", "Ashley Greene"),
        ("Angelina Jolie", "Cate Blanchett"),
        ("Natalie Portman", "Jennifer Lawrence"),
        ("Meryl Streep", "Julia Roberts"),
        ("Margot Robbie", "Emily Blunt"),
        ("Emma Watson", "Emma Roberts"),
        ("Akshay Kumar", "Tiger Shroff"),
        ("Priyanka Chopra", "Sonam Kapoor"),
        ("Irrfan Khan", "Nawazuddin Siddiqui"),
        ("Hrithik Roshan", "Akshay Kumar"),
        ("Johnny Depp", "Jack Sparrow"),
        ("Anne Hathaway", "Jennifer Lawrence"),
        ("Charlize Theron", "Nicole Kidman"),
        ("Dharmendra", "Rajesh Khanna"),
        ("Michael B. Jordan", "Chadwick Boseman"),
        ("Kareena Kapoor", "Kiara Advani"),
        ("Johnny Depp", "Orlando Bloom"),
        ("Kristen Stewart", "Taylor Lautner"),
        ("Sandra Bullock", "Reese Witherspoon"),
        ("Ryan Reynolds", "Chris Pratt"),
        ("Sunny Deol", "Akshaye Khanna"),
        ("Hrithik Roshan", "Farhan Akhtar"),
        ("Angelina Jolie", "Nicole Kidman"),
        ("Katrina Kaif", "Kareena Kapoor"),
        ("Emma Watson", "Emma Stone"),
        ("Robert Downey Jr.", "Chris Hemsworth"),
        ("Taylor Lautner", "Ashley Greene"),
        ("Vidya Balan", "Rani Mukerji"),
        ("Idris Elba", "Chadwick Boseman"),
        ("Keanu Reeves", "Christian Bale"),
        ("Scarlett Johansson", "Natalie Portman"),
        ("Scarlett Johansson", "Jennifer Lawrence"),
        ("Zendaya", "Andrew Garfield"),
        ("Vidya Balan", "Kajol"),
        ("Kangana Ranaut", "Bhumi Pednekar"),
        ("Sunny Deol", "Suniel Shetty"),
        ("Margot Robbie", "Rachel McAdams"),
        ("Scarlett Johansson", "Anne Hathaway"),
        ("Chris Pine", "Chris Rock"),
        ("Leonardo DiCaprio", "Brad Pitt"),
        ("Ajay Devgn", "Suniel Shetty"),
        ("Salman Khan", "Aamir Khan"),
        ("Kiara Advani", "Kriti Sanon"),
        ("Hrithik Roshan", "John Abraham"),
        ("Will Smith", "Denzel Washington"),
        ("Chris Hemsworth", "Mark Ruffalo"),
        ("Emma Stone", "Emma Roberts"),
        ("Amy Adams", "Rachel McAdams"),
        ("Angelina Jolie", "Charlize Theron"),
        ("Christian Bale", "Hugh Jackman"),
        ("John Abraham", "Tiger Shroff"),
        ("Robert Downey Jr.", "Chris Evans"),
        ("Tom Cruise", "Tom Hardy"),
        ("Vidya Balan", "Madhuri Dixit"),
        ("Taapsee Pannu", "Bhumi Pednekar"),
        ("Rani Mukerji", "Kajol"),
        ("Tom Cruise", "Tom Hanks"),
        ("Deepika Padukone", "Priyanka Chopra"),
        ("Priyanka Chopra", "Anushka Sharma"),
        ("Anushka Sharma", "Diana Penty"),
        ("Irrfan Khan", "Pankaj Tripathi"),
        ("Deepika Padukone", "Kareena Kapoor"),
        ("Farhan Akhtar", "Abhishek Bachchan"),
        ("Idris Elba", "Daniel Kaluuya"),
        ("Amir Khan", "Abhishek Bachchan"),
        ("Amitabh Bachchan", "Dharmendra"),
        ("Andrew Garfield", "Tobey Maguire"),
        ("Salman Khan", "Saif Ali Khan"),
        ("Jason Statham", "Sylvester Stallone"),
        ("Kareena Kapoor", "Kriti Sanon"),
        ("Meryl Streep", "Sandra Bullock"),
        ("Amitabh Bachchan", "Rajesh Khanna"),
        ("Tom Holland", "Tobey Maguire"),
        ("Leonardo DiCaprio", "George Clooney"),
        ("Amir Khan", "Hrithik Roshan"),
        ("Priyanka Chopra", "Katrina Kaif"),
        ("Kamal Haasan", "Ajith Kumar"),
        ("Charlize Theron", "Cate Blanchett"),
        ("Rajesh Khanna", "Vinod Khanna"),
    ],
    "things": [
        ("Diary", "Planner"),
        ("Postcard", "Letter"),
        ("Parcel", "Letter"),
        ("Guitar", "Ukulele"),
        ("Marker", "Chalk"),
        ("Earphones", "Speaker"),
        ("Smartphone", "Desktop"),
        ("Handbag", "Clutch"),
        ("Sneakers", "Sandals"),
        ("Spoon", "Ladle"),
        ("Bucket", "Mop Bucket"),
        ("Curtain", "Rug"),
        ("Window", "Photo Frame"),
        ("Pencil", "Chalk"),
        ("Backpack", "Briefcase"),
        ("Telescope", "Microscope"),
        ("Comb", "Hairbrush"),
        ("Keyboard", "Mouse"),
        ("Car", "Van"),
        ("Planner", "Journal"),
        ("Camera", "Telescope"),
        ("Fridge Magnet", "Sticker"),
        ("Window", "Painting"),
        ("Piano", "Harmonium"),
        ("Stool", "Bench"),
        ("Suitcase", "Rucksack"),
        ("Chair", "Stool"),
        ("Watch", "Bracelet"),
        ("Quilt", "Comforter"),
        ("Calendar", "Planner"),
        ("Candle", "Lantern"),
        ("Knife", "Ladle"),
        ("Speaker", "Microphone"),
        ("Bracelet", "Necklace"),
        ("Sandals", "Loafers"),
        ("Trolley Bag", "Rucksack"),
        ("Tablet", "Smartphone"),
        ("Umbrella", "Poncho"),
        ("Toothbrush", "Comb"),
        ("Candle", "Lamp"),
        ("Bicycle", "Scooter"),
        ("Book", "Magazine"),
        ("Broom", "Mop"),
        ("Screwdriver", "Pliers"),
        ("Blanket", "Comforter"),
        ("Candle", "Torch"),
        ("Scooter", "Rollerblades"),
        ("Mouse", "Monitor"),
        ("Football", "Cricket Ball"),
        ("Counter", "Shelf"),
        ("Lamp", "Torch"),
        ("Carpet", "Rug"),
        ("Blind", "Rug"),
        ("Harmonium", "Accordion"),
        ("Earphones", "Microphone"),
        ("Desk", "Shelf"),
        ("Curtain", "Carpet"),
        ("Sneakers", "Loafers"),
        ("Sunglasses", "Goggles"),
        ("Rucksack", "Tote Bag"),
        ("Toothbrush", "Razor"),
        ("Laptop", "Smartphone"),
        ("Chair", "Sofa"),
        ("Piano", "Accordion"),
        ("Fridge Magnet", "Bumper Sticker"),
        ("Bracelet", "Ring"),
        ("Freezer", "Microwave"),
        ("Stool", "Sofa"),
        ("Wallet", "Purse"),
        ("Bicycle", "Rollerblades"),
        ("Sunglasses", "Contact Lenses"),
        ("Violin", "Banjo"),
        ("Air Conditioner", "Heater"),
        ("Sunglasses", "Spectacles"),
        ("Suitcase", "Tote Bag"),
        ("Envelope", "Parcel"),
        ("Table", "Shelf"),
        ("Football", "Basketball"),
        ("Guitar", "Violin"),
        ("Scissors", "Shears"),
    ],
    "subjects": [
        ("Anatomy", "Pharmacology"),
        ("Economics", "Business Studies"),
        ("Interior Design", "Urban Planning"),
        ("History", "Civics"),
        ("Political Science", "Law"),
        ("Media Studies", "Broadcasting"),
        ("Forensics", "Law"),
        ("Grammar", "Rhetoric"),
        ("Electrical Engineering", "Chemical Engineering"),
        ("Anthropology", "Paleontology"),
        ("Finance", "Economics"),
        ("Literature", "Linguistics"),
        ("Music", "Dance"),
        ("Zoology", "Genetics"),
        ("Sociology", "Public Administration"),
        ("Botany", "Zoology"),
        ("Journalism", "Mass Communication"),
        ("Commerce", "Accountancy"),
        ("Journalism", "Broadcasting"),
        ("Civics", "Political Science"),
        ("Astrophysics", "Geology"),
        ("Cosmology", "Geology"),
        ("Anatomy", "Physiology"),
        ("Algebra", "Geometry"),
        ("Psychology", "Anthropology"),
        ("Grammar", "Linguistics"),
        ("Architecture", "Civil Engineering"),
        ("Accounting", "Economics"),
        ("Architecture", "Urban Planning"),
        ("Anthropology", "History"),
        ("Criminology", "Forensics"),
        ("Geography", "Civics"),
        ("Astronomy", "Geology"),
        ("Home Science", "Food Technology"),
        ("Mechanical Engineering", "Chemical Engineering"),
        ("Archaeology", "History"),
        ("Nutrition", "Dietetics"),
        ("Mass Communication", "Broadcasting"),
        ("Sociology", "Law"),
        ("Programming", "Software Engineering"),
        ("Public Administration", "Law"),
        ("Forensics", "Justice Studies"),
        ("Dance", "Theatre"),
        ("Music", "Theatre"),
        ("Art", "Music"),
        ("Commerce", "Business Studies"),
        ("Dietetics", "Home Science"),
        ("Political Science", "Public Administration"),
        ("Geography", "Political Science"),
        ("Oceanography", "Geology"),
        ("Literature", "Grammar"),
        ("Journalism", "Media Studies"),
        ("Mathematics", "Biology"),
        ("Algebra", "Calculus"),
        ("Architecture", "Interior Design"),
        ("Geology", "Environmental Science"),
        ("Mass Communication", "Media Studies"),
        ("Statistics", "Finance"),
        ("History", "Paleontology"),
        ("Coding", "Programming"),
        ("Astrophysics", "Cosmology"),
        ("Urban Planning", "Civil Engineering"),
        ("Zoology", "Ecology"),
        ("Mechanical Engineering", "Civil Engineering"),
        ("Astronomy", "Cosmology"),
        ("Art", "Dance"),
        ("Geometry", "Calculus"),
        ("Mathematics", "Physics"),
        ("Computer Science", "Programming"),
        ("Botany", "Genetics"),
        ("Physiology", "Pathology"),
        ("Economics", "Accountancy"),
        ("Ecology", "Genetics"),
        ("Statistics", "Economics"),
        ("Astronomy", "Astrophysics"),
        ("Botany", "Ecology"),
        ("Meteorology", "Environmental Science"),
        ("Civil Engineering", "Chemical Engineering"),
        ("Geometry", "Trigonometry"),
        ("Political Science", "Sociology"),
    ],
    "space": [
        ("Galaxy", "Nebula"),
        ("Space Station", "Lunar Module"),
        ("Galaxy", "Constellation"),
        ("Astronaut", "Taikonaut"),
        ("Splashdown", "Liftoff"),
        ("ISRO", "SpaceX"),
        ("Moon", "Earth"),
        ("Dwarf Planet", "Asteroid Belt"),
        ("Astronaut", "Pilot"),
        ("Exoplanet", "Dwarf Planet"),
        ("Universe", "Galaxy Cluster"),
        ("Ground Station", "Command Module"),
        ("Saturn", "Neptune"),
        ("Cosmic Ray", "Solar Wind"),
        ("Solar Wind", "Magnetosphere"),
        ("Red Giant", "Blue Giant"),
        ("Asteroid", "Meteor"),
        ("Solar System", "Galaxy Cluster"),
        ("Astronaut", "Cosmonaut"),
        ("Satellite", "Space Probe"),
        ("Telescope", "Radar"),
        ("Milky Way", "Galaxy Cluster"),
        ("Moon", "Sun"),
        ("Nebula", "Cluster"),
        ("Venus", "Mercury"),
        ("Cosmonaut", "Taikonaut"),
        ("Space Shuttle", "Lunar Module"),
        ("Trajectory", "Gravity"),
        ("White Dwarf", "Brown Dwarf"),
        ("Spacewalk", "Liftoff"),
        ("Orbit", "Gravity"),
        ("Rocket", "Space Shuttle"),
        ("Launch Pad", "Command Module"),
        ("Rocket", "Satellite"),
        ("Galaxy", "Cluster"),
        ("Neptune", "Pluto"),
        ("Wormhole", "Supernova"),
        ("Launch Pad", "Ground Station"),
        ("Blue Giant", "Brown Dwarf"),
        ("Andromeda", "Triangulum"),
        ("Saturn", "Pluto"),
        ("Mission Control", "Ground Station"),
        ("Andromeda", "Whirlpool Galaxy"),
        ("Wormhole", "Neutron Star"),
        ("Liftoff", "Docking"),
        ("Space Station", "Space Shuttle"),
        ("Moon", "Asteroid Belt"),
        ("Mission Control", "Launch Pad"),
        ("Mars", "Mercury"),
        ("Solar Wind", "Radiation Belt"),
        ("Lunar Eclipse", "Aurora"),
        ("Red Giant", "Brown Dwarf"),
        ("Spacewalk", "Docking"),
        ("Mission Control", "Command Module"),
        ("Exoplanet", "Asteroid Belt"),
        ("Telescope", "Observatory"),
        ("Comet", "Meteor"),
        ("Uranus", "Neptune"),
        ("Rocket", "Space Probe"),
        ("Mars", "Venus"),
        ("Meteor Shower", "Lunar Eclipse"),
        ("Cosmic Ray", "Radiation Belt"),
        ("Moon", "Mars"),
        ("Orbit", "Escape Velocity"),
        ("Triangulum", "Whirlpool Galaxy"),
        ("Taikonaut", "Pilot"),
        ("Milky Way", "Triangulum"),
        ("Black Hole", "Neutron Star"),
        ("ISRO", "NASA"),
        ("Mercury", "Jupiter"),
        ("Solar System", "Universe"),
        ("Orbit", "Trajectory"),
        ("Splashdown", "Docking"),
        ("Space Shuttle", "Space Probe"),
        ("Comet", "Asteroid"),
        ("NASA", "SpaceX"),
        ("Venus", "Jupiter"),
        ("Milky Way", "Whirlpool Galaxy"),
        ("SpaceX", "ESA"),
        ("Gravity", "Escape Velocity"),
    ],
    "sports": [
        ("Boxing", "Judo"),
        ("Hockey", "Ice Hockey"),
        ("Badminton", "Table Tennis"),
        ("Tennis", "Squash"),
        ("Golf", "Fencing"),
        ("Marathon", "Triathlon"),
        ("Snowboarding", "Bobsledding"),
        ("Gymnastics", "Acrobatics"),
        ("Sachin Tendulkar", "Rohit Sharma"),
        ("Surfing", "Kayaking"),
        ("Rowing", "Sailing"),
        ("Swimming", "Diving"),
        ("Badminton", "Squash"),
        ("Sachin Tendulkar", "MS Dhoni"),
        ("Chess", "Checkers"),
        ("Golf", "Archery"),
        ("Baseball", "Rounders"),
        ("Wrestling", "Judo"),
        ("Cycling", "Skateboarding"),
        ("Kho Kho", "Tug of War"),
        ("Hockey", "Lacrosse"),
        ("Kho Kho", "Sepak Takraw"),
        ("Skateboarding", "Rollerblading"),
        ("Ronaldo", "Neymar"),
        ("Weightlifting", "CrossFit"),
        ("Powerlifting", "Bodybuilding"),
        ("Volleyball", "Handball"),
        ("Surfing", "Rowing"),
        ("Rally Racing", "Drag Racing"),
        ("Rollerblading", "BMX"),
        ("Water Polo", "Synchronized Swimming"),
        ("World Cup", "Commonwealth Games"),
        ("Gymnastics", "Trampolining"),
        ("Olympics", "World Cup"),
        ("Tennis", "Table Tennis"),
        ("Acrobatics", "Cheerleading"),
        ("Triathlon", "Pentathlon"),
        ("Rugby", "Australian Football"),
        ("Virat Kohli", "MS Dhoni"),
        ("Messi", "Ronaldo"),
        ("Olympics", "Asian Games"),
        ("Neymar", "Mbappe"),
        ("Kabaddi", "Kho Kho"),
        ("Trampolining", "Acrobatics"),
        ("Basketball", "Handball"),
        ("Cricket", "Baseball"),
        ("Cricket", "Rounders"),
        ("Cricket", "Softball"),
        ("Olympics", "Commonwealth Games"),
        ("Kayaking", "Sailing"),
        ("Powerlifting", "CrossFit"),
        ("Swimming", "Water Polo"),
        ("Weightlifting", "Powerlifting"),
        ("Archery", "Shooting"),
        ("Snowboarding", "Ice Skating"),
        ("Skiing", "Bobsledding"),
        ("Ice Hockey", "Polo"),
        ("Ludo", "Checkers"),
        ("Skiing", "Ice Skating"),
        ("Softball", "Rounders"),
        ("Football", "American Football"),
        ("American Football", "Australian Football"),
        ("Carrom", "Checkers"),
        ("Diving", "Synchronized Swimming"),
        ("Basketball", "Netball"),
        ("World Cup", "Asian Games"),
        ("Kabaddi", "Tug of War"),
        ("Skiing", "Snowboarding"),
        ("Carrom", "Ludo"),
        ("Skateboarding", "BMX"),
        ("Boxing", "Wrestling"),
        ("Ronaldo", "Mbappe"),
        ("Trampolining", "Cheerleading"),
        ("Formula 1", "MotoGP"),
        ("Boxing", "Karate"),
        ("Weightlifting", "Bodybuilding"),
        ("Formula 1", "Drag Racing"),
        ("Baseball", "Softball"),
        ("Diving", "Water Polo"),
        ("Cycling", "Rollerblading"),
    ],
    "animals": [
        ("Lion", "Tiger"),
        ("Alligator", "Crocodile"),
        ("Dolphin", "Shark"),
        ("Frog", "Toad"),
        ("Butterfly", "Moth"),
        ("Wolf", "Fox"),
        ("Rabbit", "Hare"),
        ("Turtle", "Tortoise"),
        ("Crow", "Raven"),
        ("Eagle", "Hawk"),
        ("Camel", "Llama"),
        ("Donkey", "Mule"),
        ("Chimpanzee", "Gorilla"),
        ("Leopard", "Cheetah"),
        ("Ostrich", "Emu"),
        ("Seal", "Sea Lion"),
        ("Octopus", "Squid"),
        ("Bee", "Wasp"),
        ("Ant", "Termite"),
        ("Sparrow", "Finch"),
        ("Owl", "Falcon"),
        ("Zebra", "Horse"),
        ("Goat", "Sheep"),
        ("Duck", "Goose"),
        ("Peacock", "Peahen"),
        ("Parrot", "Macaw"),
        ("Panda", "Koala"),
        ("Jaguar", "Panther"),
        ("Hedgehog", "Porcupine"),
        ("Rat", "Mouse"),
        ("Kangaroo", "Wallaby"),
        ("Crab", "Lobster"),
        ("Whale", "Dolphin"),
        ("Vulture", "Eagle"),
        ("Swan", "Goose"),
        ("Penguin", "Puffin"),
        ("Hyena", "Jackal"),
        ("Bat", "Sparrow"),
        ("Snail", "Slug"),
        ("Chameleon", "Gecko"),
        ("Elephant", "Mammoth"),
        ("Cobra", "Python"),
        ("Scorpion", "Spider"),
        ("Flamingo", "Stork"),
        ("Buffalo", "Bison"),
        ("Deer", "Antelope"),
        ("Squirrel", "Chipmunk"),
        ("Pigeon", "Dove"),
        ("Woodpecker", "Kingfisher"),
        ("Beaver", "Otter"),
        ("Mongoose", "Weasel"),
        ("Toucan", "Hornbill"),
        ("Rhino", "Hippo"),
        ("Moose", "Elk"),
        ("Cat", "Lynx"),
    ],
    "places": [
        ("Paris", "Rome"),
        ("London", "Edinburgh"),
        ("New York", "Chicago"),
        ("Tokyo", "Seoul"),
        ("Dubai", "Doha"),
        ("Mumbai", "Delhi"),
        ("Bangalore", "Hyderabad"),
        ("Goa", "Kerala"),
        ("Chennai", "Kolkata"),
        ("Everest", "K2"),
        ("Sahara", "Gobi Desert"),
        ("Amazon Rainforest", "Congo Rainforest"),
        ("Nile", "Ganges"),
        ("Great Wall of China", "Hadrian's Wall"),
        ("Eiffel Tower", "Statue of Liberty"),
        ("Taj Mahal", "Red Fort"),
        ("Pyramids of Giza", "Machu Picchu"),
        ("Venice", "Amsterdam"),
        ("Bali", "Phuket"),
        ("Switzerland", "Austria"),
        ("Iceland", "Norway"),
        ("Sydney", "Melbourne"),
        ("Rio de Janeiro", "Buenos Aires"),
        ("Los Angeles", "San Francisco"),
        ("Singapore", "Hong Kong"),
        ("Kashmir", "Shimla"),
        ("Rajasthan", "Gujarat"),
        ("Agra", "Jaipur"),
        ("Maldives", "Seychelles"),
        ("Grand Canyon", "Death Valley"),
        ("Niagara Falls", "Victoria Falls"),
        ("Hawaii", "Fiji"),
        ("Kyoto", "Osaka"),
        ("Beijing", "Shanghai"),
        ("Moscow", "St. Petersburg"),
        ("Berlin", "Munich"),
        ("Barcelona", "Madrid"),
        ("Cairo", "Marrakesh"),
        ("Cape Town", "Nairobi"),
        ("Bangkok", "Hanoi"),
        ("Kathmandu", "Lhasa"),
        ("Antarctica", "Arctic"),
        ("Times Square", "Piccadilly Circus"),
        ("Central Park", "Hyde Park"),
        ("Colosseum", "Parthenon"),
        ("Great Barrier Reef", "Red Sea Reef"),
        ("Yellowstone", "Yosemite"),
        ("Vatican City", "Jerusalem"),
        ("Leh Ladakh", "Manali"),
        ("Andaman Islands", "Lakshadweep"),
    ],
}


def get_categories():
    return list(WORD_BANK.keys()) + ["mix"]


def pick_word_pair(category: str):
    if category == "mix" or category not in WORD_BANK:
        pool = [pair for pairs in WORD_BANK.values() for pair in pairs]
    else:
        pool = WORD_BANK[category]
    return random.choice(pool)
