import random

WORD_BANK = {
    "movies": [
        ('Inception', 'Interstellar'),
        ('Interstellar', 'Tenet'),
        ('Tenet', 'Memento'),
        ('Memento', 'The Martian'),
        ('The Martian', 'Gravity'),
        ('Gravity', 'Arrival'),
        ('Arrival', 'Looper'),
        ('Looper', 'Ex Machina'),
        ('Ex Machina', 'Her'),
        ('Her', 'The Social Network'),
        ('The Social Network', 'Whiplash'),
        ('Whiplash', 'Parasite'),
        ('Parasite', 'Memories of Murder'),
        ('Memories of Murder', 'Oldboy'),
        ('Oldboy', 'Train to Busan'),
        ('Train to Busan', 'The Wailing'),
        ('The Wailing', 'Drishyam'),
        ('Drishyam', 'Andhadhun'),
        ('Andhadhun', 'Kahaani'),
        ('Kahaani', 'Barfi'),
        ('Barfi', 'Queen'),
        ('Queen', 'Tamasha'),
        ('Tamasha', 'Highway'),
        ('Highway', 'Piku'),
        ('Piku', 'Article 15'),
        ('Article 15', 'Raazi'),
        ('Raazi', 'Uri'),
        ('Uri', 'War'),
        ('War', 'Pathaan'),
        ('Pathaan', 'Jawan'),
        ('Jawan', 'Animal'),
        ('Animal', 'KGF'),
        ('KGF', 'Kantara'),
        ('Kantara', 'Pushpa'),
        ('Pushpa', 'Vikram'),
        ('Vikram', 'Master'),
        ('Master', 'Leo'),
        ('Leo', 'Jailer'),
        ('Jailer', 'Kaithi'),
        ('Kaithi', 'RRR'),
        ('RRR', 'Eega'),
        ('Eega', 'Magadheera'),
        ('Magadheera', 'Dhoom'),
        ('Dhoom', 'Don'),
        ('Don', 'Race'),
        ('Race', 'Bang Bang'),
        ('Bang Bang', 'Baby'),
        ('Baby', 'Special 26'),
        ('Special 26', 'Airlift'),
        ('Airlift', 'Neerja'),
        ('Neerja', 'Tumbbad'),
        ('Tumbbad', 'Stree'),
        ('Stree', 'Bhediya'),
        ('Bhediya', 'Bhool Bhulaiyaa'),
        ('Bhool Bhulaiyaa', 'Hera Pheri'),
        ('Hera Pheri', 'Welcome'),
        ('Welcome', 'Golmaal'),
        ('Golmaal', 'Munna Bhai'),
        ('Munna Bhai', 'PK'),
        ('PK', 'Bajrangi Bhaijaan'),
        ('Bajrangi Bhaijaan', 'Singham'),
        ('Singham', 'Drishyam 2'),
        ('Drishyam 2', 'Jugjugg Jeeyo'),
        ('Jugjugg Jeeyo', 'Rocky Aur Rani'),
        ('Rocky Aur Rani', 'Gully Boy'),
        ('Gully Boy', 'Dil Dhadakne Do'),
        ('Dil Dhadakne Do', 'Kapoor & Sons'),
        ('Kapoor & Sons', 'Dear Zindagi'),
        ('Dear Zindagi', 'English Vinglish'),
        ('English Vinglish', 'Swades 2'),
        ('Swades 2', 'Lagaan 2'),
        ('Lagaan 2', 'Taare Zameen Par'),
        ('Taare Zameen Par', 'Rang De Basanti'),
        ('Rang De Basanti', 'Devdas'),
        ('Devdas', 'Om Shanti Om'),
        ('Om Shanti Om', 'Kabir Singh'),
        ('Kabir Singh', 'Simmba'),
        ('Simmba', 'Sooryavanshi'),
        ('Sooryavanshi', 'Jugni'),
        ('Jugni', 'Haider'),
    ],
    "actors": [
        ('Aamir Khan', 'Shah Rukh Khan'),
        ('Shah Rukh Khan', 'Shahid Kapoor'),
        ('Shahid Kapoor', 'Ranveer Singh'),
        ('Ranveer Singh', 'Ranbir Kapoor'),
        ('Ranbir Kapoor', 'Varun Dhawan'),
        ('Varun Dhawan', 'Ayushmann Khurrana'),
        ('Ayushmann Khurrana', 'Rajkummar Rao'),
        ('Rajkummar Rao', 'Vicky Kaushal'),
        ('Vicky Kaushal', 'Nawazuddin Siddiqui'),
        ('Nawazuddin Siddiqui', 'Pankaj Tripathi'),
        ('Pankaj Tripathi', 'Manoj Bajpayee'),
        ('Manoj Bajpayee', 'Irrfan Khan'),
        ('Irrfan Khan', 'R. Madhavan'),
        ('R. Madhavan', 'Dhanush'),
        ('Dhanush', 'Vijay'),
        ('Vijay', 'Suriya'),
        ('Suriya', 'Karthi'),
        ('Karthi', 'Yash'),
        ('Yash', 'Prabhas'),
        ('Prabhas', 'Allu Arjun'),
        ('Allu Arjun', 'Ram Charan'),
        ('Ram Charan', 'Jr NTR'),
        ('Jr NTR', 'Nani'),
        ('Nani', 'Fahadh Faasil'),
        ('Fahadh Faasil', 'Mohanlal'),
        ('Mohanlal', 'Mammootty'),
        ('Mammootty', 'Kamal Haasan'),
        ('Kamal Haasan', 'Rajinikanth'),
        ('Rajinikanth', 'Chiranjeevi'),
        ('Chiranjeevi', 'Katrina Kaif'),
        ('Katrina Kaif', 'Anushka Sharma'),
        ('Anushka Sharma', 'Alia Bhatt'),
        ('Alia Bhatt', 'Deepika Padukone'),
        ('Deepika Padukone', 'Taapsee Pannu'),
        ('Taapsee Pannu', 'Kriti Sanon'),
        ('Kriti Sanon', 'Kangana Ranaut'),
        ('Kangana Ranaut', 'Radhika Apte'),
        ('Radhika Apte', 'Tabu'),
        ('Tabu', 'Shefali Shah'),
        ('Shefali Shah', 'Vidya Balan'),
        ('Vidya Balan', 'Richa Chadha'),
        ('Richa Chadha', 'Bhumi Pednekar'),
        ('Bhumi Pednekar', 'Rani Mukerji'),
        ('Rani Mukerji', 'Kajol'),
        ('Kajol', 'Aishwarya Rai'),
        ('Aishwarya Rai', 'Rekha'),
        ('Rekha', 'Sridevi'),
        ('Sridevi', 'Madhuri Dixit'),
        ('Madhuri Dixit', 'Juhi Chawla'),
        ('Juhi Chawla', 'Amitabh Bachchan'),
        ('Amitabh Bachchan', 'Naseeruddin Shah'),
        ('Naseeruddin Shah', 'Om Puri'),
        ('Om Puri', 'Anil Kapoor'),
        ('Anil Kapoor', 'Suniel Shetty'),
        ('Suniel Shetty', 'Jackie Shroff'),
        ('Jackie Shroff', 'Sanjay Dutt'),
        ('Sanjay Dutt', 'Govinda'),
        ('Govinda', 'Mithun Chakraborty'),
        ('Mithun Chakraborty', 'Nana Patekar'),
        ('Nana Patekar', 'Akshay Khanna'),
        ('Akshay Khanna', 'Saif Ali Khan'),
        ('Saif Ali Khan', 'John Abraham'),
        ('John Abraham', 'Varun Sharma'),
        ('Varun Sharma', 'Rajpal Yadav'),
        ('Rajpal Yadav', 'Chris Evans'),
        ('Chris Evans', 'Chris Pratt'),
        ('Chris Pratt', 'Ryan Gosling'),
        ('Ryan Gosling', 'Bradley Cooper'),
        ('Bradley Cooper', 'Matt Damon'),
        ('Matt Damon', 'Christian Bale'),
        ('Christian Bale', 'Hugh Jackman'),
        ('Hugh Jackman', 'Dwayne Johnson'),
        ('Dwayne Johnson', 'Jason Momoa'),
        ('Jason Momoa', 'Gal Gadot'),
        ('Gal Gadot', 'Margot Robbie'),
        ('Margot Robbie', 'Emma Stone'),
        ('Emma Stone', 'Florence Pugh'),
        ('Florence Pugh', 'Tom Hiddleston'),
        ('Tom Hiddleston', 'Benedict Cumberbatch'),
        ('Benedict Cumberbatch', 'Cillian Murphy'),
    ],
    "things": [
        ('Notebook', 'Sketchbook'),
        ('Sketchbook', 'Stapler'),
        ('Stapler', 'Hole Punch'),
        ('Hole Punch', 'Ruler'),
        ('Ruler', 'Eraser'),
        ('Eraser', 'Highlighter'),
        ('Highlighter', 'Marker Pen'),
        ('Marker Pen', 'Water Bottle'),
        ('Water Bottle', 'Thermos'),
        ('Thermos', 'Backpack'),
        ('Backpack', 'Messenger Bag'),
        ('Messenger Bag', 'Headphones'),
        ('Headphones', 'Earbuds'),
        ('Earbuds', 'Remote'),
        ('Remote', 'Game Controller'),
        ('Game Controller', 'Flashlight'),
        ('Flashlight', 'Lantern'),
        ('Lantern', 'Mirror'),
        ('Mirror', 'Comb'),
        ('Comb', 'Hair Dryer'),
        ('Hair Dryer', 'Shampoo'),
        ('Shampoo', 'Soap'),
        ('Soap', 'Towel'),
        ('Towel', 'Pillow'),
        ('Pillow', 'Mattress'),
        ('Mattress', 'Bedsheet'),
        ('Bedsheet', 'Curtain'),
        ('Curtain', 'Doormat'),
        ('Doormat', 'Bookshelf'),
        ('Bookshelf', 'Drawer'),
        ('Drawer', 'Cabinet'),
        ('Cabinet', 'Bowl'),
        ('Bowl', 'Plate'),
        ('Plate', 'Mug'),
        ('Mug', 'Glass'),
        ('Glass', 'Fork'),
        ('Fork', 'Chopsticks'),
        ('Chopsticks', 'Kettle'),
        ('Kettle', 'Toaster'),
        ('Toaster', 'Blender'),
        ('Blender', 'Mixer'),
        ('Mixer', 'Oven'),
        ('Oven', 'Stove'),
        ('Stove', 'Bicycle'),
        ('Bicycle', 'Helmet'),
        ('Helmet', 'Skateboard'),
        ('Skateboard', 'Scooter'),
        ('Scooter', 'Raincoat'),
        ('Raincoat', 'Boots'),
        ('Boots', 'Jacket'),
        ('Jacket', 'Hoodie'),
        ('Hoodie', 'Cap'),
        ('Cap', 'Scarf'),
        ('Scarf', 'Gloves'),
        ('Gloves', 'Belt'),
        ('Belt', 'Tie'),
        ('Tie', 'Socks'),
        ('Socks', 'Jeans'),
        ('Jeans', 'Shirt'),
        ('Shirt', 'Camera'),
        ('Camera', 'Tripod'),
        ('Tripod', 'Binoculars'),
        ('Binoculars', 'Compass'),
        ('Compass', 'Map'),
        ('Map', 'Calculator'),
        ('Calculator', 'Printer'),
        ('Printer', 'Scanner'),
        ('Scanner', 'Projector'),
        ('Projector', 'Router'),
        ('Router', 'Charger'),
        ('Charger', 'Power Bank'),
        ('Power Bank', 'USB Drive'),
        ('USB Drive', 'Hard Drive'),
        ('Hard Drive', 'Keyboard'),
        ('Keyboard', 'Trackpad'),
        ('Trackpad', 'Monitor'),
        ('Monitor', 'Tablet'),
        ('Tablet', 'Smartwatch'),
        ('Smartwatch', 'Suitcase'),
        ('Suitcase', 'Duffle Bag'),
    ],
    "subjects": [
        ('Calculus', 'Trigonometry'),
        ('Trigonometry', 'Statistics'),
        ('Statistics', 'Probability'),
        ('Probability', 'Discrete Mathematics'),
        ('Discrete Mathematics', 'Data Structures'),
        ('Data Structures', 'Algorithms'),
        ('Algorithms', 'Database Systems'),
        ('Database Systems', 'Operating Systems'),
        ('Operating Systems', 'Computer Networks'),
        ('Computer Networks', 'Cybersecurity'),
        ('Cybersecurity', 'Artificial Intelligence'),
        ('Artificial Intelligence', 'Machine Learning'),
        ('Machine Learning', 'Cloud Computing'),
        ('Cloud Computing', 'Web Development'),
        ('Web Development', 'Mobile Development'),
        ('Mobile Development', 'Game Design'),
        ('Game Design', 'Robotics'),
        ('Robotics', 'Electronics'),
        ('Electronics', 'Thermodynamics'),
        ('Thermodynamics', 'Mechanics'),
        ('Mechanics', 'Optics'),
        ('Optics', 'Quantum Physics'),
        ('Quantum Physics', 'Organic Chemistry'),
        ('Organic Chemistry', 'Biochemistry'),
        ('Biochemistry', 'Microbiology'),
        ('Microbiology', 'Genomics'),
        ('Genomics', 'Ecology'),
        ('Ecology', 'Environmental Science'),
        ('Environmental Science', 'Geography'),
        ('Geography', 'Geology'),
        ('Geology', 'Meteorology'),
        ('Meteorology', 'Astronomy'),
        ('Astronomy', 'Astrophysics'),
        ('Astrophysics', 'Psychology'),
        ('Psychology', 'Sociology'),
        ('Sociology', 'Philosophy'),
        ('Philosophy', 'Ethics'),
        ('Ethics', 'Anthropology'),
        ('Anthropology', 'Archaeology'),
        ('Archaeology', 'History'),
        ('History', 'Economics'),
        ('Economics', 'Marketing'),
        ('Marketing', 'Management'),
        ('Management', 'Entrepreneurship'),
        ('Entrepreneurship', 'Accounting'),
        ('Accounting', 'Banking'),
        ('Banking', 'Journalism'),
        ('Journalism', 'Advertising'),
        ('Advertising', 'Photography'),
        ('Photography', 'Film Studies'),
        ('Film Studies', 'Graphic Design'),
        ('Graphic Design', 'Fine Arts'),
        ('Fine Arts', 'Architecture'),
        ('Architecture', 'Linguistics'),
        ('Linguistics', 'Literature'),
        ('Literature', 'Creative Writing'),
        ('Creative Writing', 'Political Theory'),
        ('Political Theory', 'International Relations'),
        ('International Relations', 'Public Policy'),
        ('Public Policy', 'Law'),
        ('Law', 'Criminology'),
        ('Criminology', 'Forensic Science'),
        ('Forensic Science', 'Medicine'),
        ('Medicine', 'Anatomy'),
        ('Anatomy', 'Physiology'),
        ('Physiology', 'Pharmacology'),
        ('Pharmacology', 'Nutrition'),
        ('Nutrition', 'Agriculture'),
        ('Agriculture', 'Horticulture'),
        ('Horticulture', 'Veterinary Science'),
        ('Veterinary Science', 'Music Theory'),
        ('Music Theory', 'Classical Dance'),
        ('Classical Dance', 'Theatre Studies'),
        ('Theatre Studies', 'Animation'),
        ('Animation', 'Typography'),
        ('Typography', 'Astronomy Lab'),
        ('Astronomy Lab', 'Business Analytics'),
        ('Business Analytics', 'Operations Research'),
        ('Operations Research', 'Human Resources'),
        ('Human Resources', 'Supply Chain'),
    ],
    "space": [
        ('Sun', 'Mercury'),
        ('Mercury', 'Venus'),
        ('Venus', 'Earth'),
        ('Earth', 'Mars'),
        ('Mars', 'Jupiter'),
        ('Jupiter', 'Saturn'),
        ('Saturn', 'Uranus'),
        ('Uranus', 'Neptune'),
        ('Neptune', 'Pluto'),
        ('Pluto', 'Ceres'),
        ('Ceres', 'Eris'),
        ('Eris', 'Moon'),
        ('Moon', 'Europa'),
        ('Europa', 'Titan'),
        ('Titan', 'Ganymede'),
        ('Ganymede', 'Callisto'),
        ('Callisto', 'Io'),
        ('Io', 'Phobos'),
        ('Phobos', 'Deimos'),
        ('Deimos', 'Asteroid'),
        ('Asteroid', 'Comet'),
        ('Comet', 'Meteoroid'),
        ('Meteoroid', 'Meteor'),
        ('Meteor', 'Meteorite'),
        ('Meteorite', 'Nebula'),
        ('Nebula', 'Quasar'),
        ('Quasar', 'Pulsar'),
        ('Pulsar', 'Galaxy'),
        ('Galaxy', 'Supercluster'),
        ('Supercluster', 'Black Hole'),
        ('Black Hole', 'White Hole'),
        ('White Hole', 'Neutron Star'),
        ('Neutron Star', 'White Dwarf'),
        ('White Dwarf', 'Red Dwarf'),
        ('Red Dwarf', 'Red Giant'),
        ('Red Giant', 'Supernova'),
        ('Supernova', 'Solar Flare'),
        ('Solar Flare', 'Solar Wind'),
        ('Solar Wind', 'Aurora'),
        ('Aurora', 'Orbit'),
        ('Orbit', 'Eclipse'),
        ('Eclipse', 'Equinox'),
        ('Equinox', 'Solstice'),
        ('Solstice', 'Rocket'),
        ('Rocket', 'Spacecraft'),
        ('Spacecraft', 'Space Probe'),
        ('Space Probe', 'Space Telescope'),
        ('Space Telescope', 'Space Station'),
        ('Space Station', 'Lander'),
        ('Lander', 'Rover'),
        ('Rover', 'Spacesuit'),
        ('Spacesuit', 'Spacewalk'),
        ('Spacewalk', 'Launch Pad'),
        ('Launch Pad', 'Mission Control'),
        ('Mission Control', 'Ground Station'),
        ('Ground Station', 'Satellite'),
        ('Satellite', 'Navigation System'),
        ('Navigation System', 'Gravity'),
        ('Gravity', 'Dark Matter'),
        ('Dark Matter', 'Dark Energy'),
        ('Dark Energy', 'Exoplanet'),
        ('Exoplanet', 'Wormhole'),
        ('Wormhole', 'Light Year'),
        ('Light Year', 'Cosmic Ray'),
        ('Cosmic Ray', 'Radiation Belt'),
        ('Radiation Belt', 'Lunar Module'),
        ('Lunar Module', 'Command Module'),
        ('Command Module', 'Docking'),
        ('Docking', 'Reentry'),
        ('Reentry', 'Liftoff'),
        ('Liftoff', 'Astronaut'),
        ('Astronaut', 'Cosmonaut'),
        ('Cosmonaut', 'Taikonaut'),
        ('Taikonaut', 'Observatory'),
        ('Observatory', 'Telescope'),
        ('Telescope', 'Radio Telescope'),
        ('Radio Telescope', 'Planetarium'),
        ('Planetarium', 'Milky Way'),
        ('Milky Way', 'Andromeda'),
        ('Andromeda', 'Constellation'),
    ],
    "sports": [
        ('Cricket', 'Football'),
        ('Football', 'Basketball'),
        ('Basketball', 'Volleyball'),
        ('Volleyball', 'Handball'),
        ('Handball', 'Rugby'),
        ('Rugby', 'Baseball'),
        ('Baseball', 'Softball'),
        ('Softball', 'Tennis'),
        ('Tennis', 'Badminton'),
        ('Badminton', 'Squash'),
        ('Squash', 'Table Tennis'),
        ('Table Tennis', 'Hockey'),
        ('Hockey', 'Ice Hockey'),
        ('Ice Hockey', 'Field Hockey'),
        ('Field Hockey', 'Golf'),
        ('Golf', 'Boxing'),
        ('Boxing', 'Kickboxing'),
        ('Kickboxing', 'Karate'),
        ('Karate', 'Taekwondo'),
        ('Taekwondo', 'Judo'),
        ('Judo', 'Wrestling'),
        ('Wrestling', 'Fencing'),
        ('Fencing', 'Archery'),
        ('Archery', 'Shooting'),
        ('Shooting', 'Swimming'),
        ('Swimming', 'Diving'),
        ('Diving', 'Water Polo'),
        ('Water Polo', 'Rowing'),
        ('Rowing', 'Sailing'),
        ('Sailing', 'Kayaking'),
        ('Kayaking', 'Canoeing'),
        ('Canoeing', 'Surfing'),
        ('Surfing', 'Skateboarding'),
        ('Skateboarding', 'Snowboarding'),
        ('Snowboarding', 'Skiing'),
        ('Skiing', 'Cycling'),
        ('Cycling', 'BMX'),
        ('BMX', 'Athletics'),
        ('Athletics', 'Marathon'),
        ('Marathon', 'Triathlon'),
        ('Triathlon', 'Pentathlon'),
        ('Pentathlon', 'Gymnastics'),
        ('Gymnastics', 'Trampolining'),
        ('Trampolining', 'Weightlifting'),
        ('Weightlifting', 'Powerlifting'),
        ('Powerlifting', 'Bodybuilding'),
        ('Bodybuilding', 'CrossFit'),
        ('CrossFit', 'Kabaddi'),
        ('Kabaddi', 'Kho Kho'),
        ('Kho Kho', 'Carrom'),
        ('Carrom', 'Chess'),
        ('Chess', 'Checkers'),
        ('Checkers', 'Ludo'),
        ('Ludo', 'Formula One'),
        ('Formula One', 'MotoGP'),
        ('MotoGP', 'Rally'),
        ('Rally', 'Drag Racing'),
        ('Drag Racing', 'Horse Racing'),
        ('Horse Racing', 'Polo'),
        ('Polo', 'Equestrian'),
        ('Equestrian', 'Climbing'),
        ('Climbing', 'Mountaineering'),
        ('Mountaineering', 'Parkour'),
        ('Parkour', 'Cheerleading'),
        ('Cheerleading', 'Netball'),
        ('Netball', 'Sepak Takraw'),
        ('Sepak Takraw', 'Ultimate Frisbee'),
        ('Ultimate Frisbee', 'Darts'),
        ('Darts', 'Snooker'),
        ('Snooker', 'Billiards'),
        ('Billiards', 'Bowling'),
        ('Bowling', 'Fishing'),
        ('Fishing', 'Rowing'),
        ('Rowing', 'Motorsport'),
        ('Motorsport', 'Racing'),
        ('Racing', 'Sprint'),
        ('Sprint', 'Hurdles'),
        ('Hurdles', 'Relay'),
        ('Relay', 'Long Jump'),
        ('Long Jump', 'Cricket'),
    ],
    "animals": [
        ('Cheetah', 'Leopard'),
        ('Leopard', 'Jaguar'),
        ('Jaguar', 'Panther'),
        ('Panther', 'Lion'),
        ('Lion', 'Tiger'),
        ('Tiger', 'Cougar'),
        ('Cougar', 'Wolf'),
        ('Wolf', 'Fox'),
        ('Fox', 'Coyote'),
        ('Coyote', 'Jackal'),
        ('Jackal', 'Hyena'),
        ('Hyena', 'Bear'),
        ('Bear', 'Panda'),
        ('Panda', 'Koala'),
        ('Koala', 'Kangaroo'),
        ('Kangaroo', 'Wallaby'),
        ('Wallaby', 'Rabbit'),
        ('Rabbit', 'Hare'),
        ('Hare', 'Squirrel'),
        ('Squirrel', 'Chipmunk'),
        ('Chipmunk', 'Mouse'),
        ('Mouse', 'Rat'),
        ('Rat', 'Hamster'),
        ('Hamster', 'Guinea Pig'),
        ('Guinea Pig', 'Deer'),
        ('Deer', 'Moose'),
        ('Moose', 'Elk'),
        ('Elk', 'Antelope'),
        ('Antelope', 'Gazelle'),
        ('Gazelle', 'Giraffe'),
        ('Giraffe', 'Zebra'),
        ('Zebra', 'Horse'),
        ('Horse', 'Donkey'),
        ('Donkey', 'Mule'),
        ('Mule', 'Camel'),
        ('Camel', 'Llama'),
        ('Llama', 'Alpaca'),
        ('Alpaca', 'Elephant'),
        ('Elephant', 'Rhinoceros'),
        ('Rhinoceros', 'Hippopotamus'),
        ('Hippopotamus', 'Buffalo'),
        ('Buffalo', 'Bison'),
        ('Bison', 'Gorilla'),
        ('Gorilla', 'Chimpanzee'),
        ('Chimpanzee', 'Orangutan'),
        ('Orangutan', 'Baboon'),
        ('Baboon', 'Monkey'),
        ('Monkey', 'Dolphin'),
        ('Dolphin', 'Porpoise'),
        ('Porpoise', 'Whale'),
        ('Whale', 'Shark'),
        ('Shark', 'Ray'),
        ('Ray', 'Seal'),
        ('Seal', 'Walrus'),
        ('Walrus', 'Otter'),
        ('Otter', 'Beaver'),
        ('Beaver', 'Crocodile'),
        ('Crocodile', 'Alligator'),
        ('Alligator', 'Turtle'),
        ('Turtle', 'Tortoise'),
        ('Tortoise', 'Lizard'),
        ('Lizard', 'Gecko'),
        ('Gecko', 'Chameleon'),
        ('Chameleon', 'Snake'),
        ('Snake', 'Python'),
        ('Python', 'Cobra'),
        ('Cobra', 'Frog'),
        ('Frog', 'Toad'),
        ('Toad', 'Salamander'),
        ('Salamander', 'Butterfly'),
        ('Butterfly', 'Moth'),
        ('Moth', 'Bee'),
        ('Bee', 'Wasp'),
        ('Wasp', 'Ant'),
        ('Ant', 'Beetle'),
        ('Beetle', 'Owl'),
        ('Owl', 'Eagle'),
        ('Eagle', 'Hawk'),
        ('Hawk', 'Falcon'),
        ('Falcon', 'Parrot'),
    ],
    "places": [
        ('Lisbon', 'Madrid'),
        ('Madrid', 'Barcelona'),
        ('Barcelona', 'Paris'),
        ('Paris', 'Vienna'),
        ('Vienna', 'Prague'),
        ('Prague', 'Budapest'),
        ('Budapest', 'Athens'),
        ('Athens', 'Rome'),
        ('Rome', 'Milan'),
        ('Milan', 'Venice'),
        ('Venice', 'Berlin'),
        ('Berlin', 'Munich'),
        ('Munich', 'Amsterdam'),
        ('Amsterdam', 'Brussels'),
        ('Brussels', 'London'),
        ('London', 'Dublin'),
        ('Dublin', 'Edinburgh'),
        ('Edinburgh', 'Oslo'),
        ('Oslo', 'Stockholm'),
        ('Stockholm', 'Helsinki'),
        ('Helsinki', 'Copenhagen'),
        ('Copenhagen', 'Reykjavik'),
        ('Reykjavik', 'Moscow'),
        ('Moscow', 'Istanbul'),
        ('Istanbul', 'Cairo'),
        ('Cairo', 'Nairobi'),
        ('Nairobi', 'Cape Town'),
        ('Cape Town', 'Casablanca'),
        ('Casablanca', 'Marrakesh'),
        ('Marrakesh', 'Dubai'),
        ('Dubai', 'Abu Dhabi'),
        ('Abu Dhabi', 'Doha'),
        ('Doha', 'Muscat'),
        ('Muscat', 'Kathmandu'),
        ('Kathmandu', 'Thimphu'),
        ('Thimphu', 'Colombo'),
        ('Colombo', 'Dhaka'),
        ('Dhaka', 'Bangkok'),
        ('Bangkok', 'Hanoi'),
        ('Hanoi', 'Singapore'),
        ('Singapore', 'Kuala Lumpur'),
        ('Kuala Lumpur', 'Jakarta'),
        ('Jakarta', 'Manila'),
        ('Manila', 'Tokyo'),
        ('Tokyo', 'Kyoto'),
        ('Kyoto', 'Seoul'),
        ('Seoul', 'Beijing'),
        ('Beijing', 'Shanghai'),
        ('Shanghai', 'Sydney'),
        ('Sydney', 'Melbourne'),
        ('Melbourne', 'Auckland'),
        ('Auckland', 'Honolulu'),
        ('Honolulu', 'Vancouver'),
        ('Vancouver', 'Toronto'),
        ('Toronto', 'Chicago'),
        ('Chicago', 'Boston'),
        ('Boston', 'Seattle'),
        ('Seattle', 'Miami'),
        ('Miami', 'Las Vegas'),
        ('Las Vegas', 'Mexico City'),
        ('Mexico City', 'Lima'),
        ('Lima', 'Santiago'),
        ('Santiago', 'Buenos Aires'),
        ('Buenos Aires', 'Rio de Janeiro'),
        ('Rio de Janeiro', 'Sao Paulo'),
        ('Sao Paulo', 'Cusco'),
        ('Cusco', 'Amazon Basin'),
        ('Amazon Basin', 'Sahara Desert'),
        ('Sahara Desert', 'Gobi Desert'),
        ('Gobi Desert', 'Himalayas'),
        ('Himalayas', 'Alps'),
        ('Alps', 'Andes'),
        ('Andes', 'Nile River'),
        ('Nile River', 'Danube'),
        ('Danube', 'Amazon River'),
        ('Amazon River', 'Victoria Falls'),
        ('Victoria Falls', 'Iguazu Falls'),
        ('Iguazu Falls', 'Grand Canyon'),
        ('Grand Canyon', 'Great Barrier Reef'),
        ('Great Barrier Reef', 'Galapagos Islands'),
    ],
}


def get_categories():
    return list(WORD_BANK.keys()) + ["mix"]


def pick_word_pair(category: str):
    if category == "mix" or category not in WORD_BANK:
        pool = [pair for pairs in WORD_BANK.values() for pair in pairs]
    else:
        pool = WORD_BANK[category]
    return random.choice(pool)
